FROM node:20-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install

EXPOSE 4200

CMD [ "sh" ]

# docker build -t MovieManager:v1 .

# docker image ls

# docker run -it --name moviemanager-container -p 3000:80 moviemanager:v1

# npm install -g @angular/cli

# ng serve --host 0.0.0.0

# docker stop 

# docker rm 